services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hash-generation-service
    ports:
      - "8080:8080"
    environment:
      HASH_GENERATION_DB_URL: jdbc:postgresql://db:5432/hash-generation-db
      HASH_GENERATION_DB_USERNAME: postgres
      HASH_GENERATION_DB_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:latest
    container_name: hash-generation-db
    environment:
      POSTGRES_DB: hash-generation-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - hash-generation-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  hash-generation-db:
    driver: local
